### ISSUE TITLE
Error : raha/pipeline_3_(detailed_demo).ipynb 

### ISSUE THREAD

**Issue by vishvapalsinh** [BigDaMa/raha#15]
I am not able to find folder models in supplementaries on the repository.   

PRETRAINED_VALUE_BASED_MODELS_PATH = "/media/mohammad/C20E45C80E45B5E7/Projects/raha/supplementaries/models/pretrained_value_based_models_small.dictionary"

**Comment by m-mahdavi** [comment]
Since these pretrained models were bulky, we were not able to upload them here. I suggest running our system without a pretrained model. Otherwise, you have to create these pretrained models as detailed in the research paper.
